spring:
  cloud:
    stream:
      bindings:
        input:
          destination: ${KINESIS_STREAM_NAME}
          group: test-kinesis-group
          content-type: text/plain
  data:
    mongodb:
      uri: mongodb://root:example@localhost:27017/test?authSource=admin
cloud:
  aws:
    credentials:
      accessKey: ${AWS_ACCESS_KEY}
      secretKey: ${AWS_SECRET_KEY}
    region:
      static: ${AWS_REGION}
      auto: false
      use-default-aws-region-chain: true
    stack:
      auto: false

logging:
  level:
    com.amazonaws.util.EC2MetadataUtils: error
    com.amazonaws.internal.InstanceMetadataServiceResourceFetcher: error

