server:
  port: 9000

spring:
  data:
    mongodb:
      uri: mongodb://root:example@localhost:27017/test?authSource=admin


logging:
  level:
    com.amazonaws.util.EC2MetadataUtils: error
    com.amazonaws.internal.InstanceMetadataServiceResourceFetcher: error