spring:
  cloud:
    stream:
      bindings:
        output:
          destination: ${KINESIS_STREAM_NAME}
          content-type: text/plain
cloud:
  aws:
    credentials:
      accessKey: ${AWS_ACCESS_KEY}
      secretKey: ${AWS_SECRET_KEY}
    region:
      static: ${AWS_REGION}
      auto: false
      use-default-aws-region-chain: true
    stack:
      auto: false

logging:
  level:
    com.amazonaws.util.EC2MetadataUtils: error
    com.amazonaws.internal.InstanceMetadataServiceResourceFetcher: error

kinesis:
  source:
    filePath: resident-samples.log